### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by jtrillos** [pyvandenbussche/lovScripts#1]
Hi, I am trying to install the lovScripts, but I always receive an error. I think it is because the project does not have any resources (lov.rdf, lov.nq, lov.n3). Can you help me?

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.9:jar (attach-javadocs) on project lovscripts: MavenReportException: Error while creating archive:
[ERROR] Exit code: 1 - /root/lovScripts/src/main/java/org/lov/LovBotVocabAnalyser.java:38: warning: no @param for vocabularyversionURL
[ERROR] public static VocabularySuggest analyseVersion(String vocabularyversionURL, String vocabularyURI, String vocabularyNsp, Lang lang, Properties lovConfig) throws Exception{
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/LovBotVocabAnalyser.java:38: warning: no @param for vocabularyURI
[ERROR] public static VocabularySuggest analyseVersion(String vocabularyversionURL, String vocabularyURI, String vocabularyNsp, Lang lang, Properties lovConfig) throws Exception{
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/LovBotVocabAnalyser.java:38: warning: no @param for vocabularyNsp
[ERROR] public static VocabularySuggest analyseVersion(String vocabularyversionURL, String vocabularyURI, String vocabularyNsp, Lang lang, Properties lovConfig) throws Exception{
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/LovBotVocabAnalyser.java:38: warning: no @param for lang
[ERROR] public static VocabularySuggest analyseVersion(String vocabularyversionURL, String vocabularyURI, String vocabularyNsp, Lang lang, Properties lovConfig) throws Exception{
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/LovBotVocabAnalyser.java:38: warning: no @param for lovConfig
[ERROR] public static VocabularySuggest analyseVersion(String vocabularyversionURL, String vocabularyURI, String vocabularyNsp, Lang lang, Properties lovConfig) throws Exception{
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/LovBotVocabAnalyser.java:38: warning: no @return
[ERROR] public static VocabularySuggest analyseVersion(String vocabularyversionURL, String vocabularyURI, String vocabularyNsp, Lang lang, Properties lovConfig) throws Exception{
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/LovBotVocabAnalyser.java:38: warning: no @throws for java.lang.Exception
[ERROR] public static VocabularySuggest analyseVersion(String vocabularyversionURL, String vocabularyURI, String vocabularyNsp, Lang lang, Properties lovConfig) throws Exception{
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/LovBotVocabAnalyser.java:46: warning: no @param for vocabularyURI
[ERROR] public static VocabularySuggest analyseVocabURI(String vocabularyURI, Properties lovConfig) throws Exception{
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/LovBotVocabAnalyser.java:46: warning: no @param for lovConfig
[ERROR] public static VocabularySuggest analyseVocabURI(String vocabularyURI, Properties lovConfig) throws Exception{
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/LovBotVocabAnalyser.java:46: warning: no @return
[ERROR] public static VocabularySuggest analyseVocabURI(String vocabularyURI, Properties lovConfig) throws Exception{
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/LovBotVocabAnalyser.java:46: warning: no @throws for java.lang.Exception
[ERROR] public static VocabularySuggest analyseVocabURI(String vocabularyURI, Properties lovConfig) throws Exception{
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/StatementHelper.java:23: warning: no description for @param
[ERROR] * @param resourceSubject
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/StatementHelper.java:24: warning: no description for @param
[ERROR] * @param property
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/StatementHelper.java:25: warning: no description for @param
[ERROR] * @param literalValue
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/StatementHelper.java:27: warning: no description for @param
[ERROR] * @param lang
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/vocidex/JSONHelper.java:39: warning: no @param for fileName
[ERROR] public static String readFile(String fileName) {
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/vocidex/JSONHelper.java:39: warning: no @return
[ERROR] public static String readFile(String fileName) {
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/vocidex/describers/LabelDescriber.java:41: warning: no @param for uri
[ERROR] public String synthesizeLabelFromURI(String uri) {
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/vocidex/describers/LabelDescriber.java:41: warning: no @return
[ERROR] public String synthesizeLabelFromURI(String uri) {
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/vocidex/describers/StrLiteralDescriber.java:111: warning: no @param for uri
[ERROR] public String synthesizeLabelFromURI(String uri) {
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/vocidex/describers/StrLiteralDescriber.java:111: warning: no @return
[ERROR] public String synthesizeLabelFromURI(String uri) {
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/vocidex/extract/AgentsExtractor.java:30: warning: no @return
[ERROR] public Iterator<VocidexDocument> persons() {
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/vocidex/extract/AgentsExtractor.java:37: warning: no @return
[ERROR] public Iterator<VocidexDocument> organizations() {
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/vocidex/extract/AgentsExtractor.java:43: warning: no description for @return
[ERROR] * @return
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/vocidex/extract/LOVWrapper.java:34: warning: no @param for termMetricsDescriber
[ERROR] public LOVWrapper(VocabularyTermExtractor wrapped, Collection<Resource> eligibleResources, final ObjectNode vocabularyDescription, final LOVTermMetricsDescriber termMetricsDescriber) {
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/vocidex/extract/VocabularyTermExtractor.java:41: warning: no @return
[ERROR] public Iterator<VocidexDocument> classes() {
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/vocidex/extract/VocabularyTermExtractor.java:48: warning: no @return
[ERROR] public Iterator<VocidexDocument> properties() {
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/vocidex/extract/VocabularyTermExtractor.java:55: warning: no @return
[ERROR] public Iterator<VocidexDocument> datatypes() {
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/vocidex/extract/VocabularyTermExtractor.java:62: warning: no @return
[ERROR] public Iterator<VocidexDocument> instances() {
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/vocidex/extract/VocabularyTermExtractor.java:32: warning: no @param for tag
[ERROR] public VocabularyTermExtractor(SPARQLRunner source, String prefix, String tag) {
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/vocidex/VocidexIndex.java:86: warning: no @param for document
[ERROR] public String addDocument(VocidexDocument document) {
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/rdf2mongo/extractors/AgentsExtractor.java:31: warning: no @return
[ERROR] public Iterator<Agent> persons() {
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/rdf2mongo/extractors/AgentsExtractor.java:38: warning: no @return
[ERROR] public Iterator<Agent> organizations() {
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/rdf2mongo/extractors/AgentsExtractor.java:45: warning: no @return
[ERROR] public Iterator<Agent> swAgents() {
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/rdf2mongo/extractors/LanguagesExtractor.java:28: warning: no @return
[ERROR] public Iterator<Language> getLanguages() {
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/rdf2mongo/extractors/UsersExtractor.java:31: warning: no @return
[ERROR] public Iterator<User> getcurators() {
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/rdf2mongo/iterators/AgentsDescriberIterator.java:14: error: reference not found
[ERROR] * {@link Vocabulary}s by calling a {@link Describer}
[ERROR] ^
[ERROR] /root/lovScripts/src/main/java/org/lov/rdf2mongo/iterators/UsersDescriberIterator.java:13: error: reference not found
[ERROR] * {@link User}s by calling a {@link Describer}
[ERROR] ^
[ERROR]

**Comment by pyvandenbussche** [comment]
Hi,

All scripts require as input the configFilePath (path to lov.config). Then depending on the script (in org.lov.cli) it will then access MongoDB or lov.n3 or lov.nq files. 

If you are missing an initial lov.nq/lov.n3, you can experiment using the one from lov.okfn.org available for download at this page: http://lov.okfn.org/dataset/lov/sparql (data dumps on the right)

**Comment by jtrillos** [comment]
Hi again,
I do not know where I can find the folders for VERSIONS_DIR_PATH, VERSIONS_TEMP_PATH ? there is no versions folder in lov. But there is a vcommons in lov. I tried with this one. But the error persist. Also I put the n3 and nq files and change the lov.config to the path that there is saved but like I said the error persist.

**Comment by jtrillos** [comment]
I find the error 
I just need to comment in pom.xml  insert in line 135
`<plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-javadoc-plugin</artifactId>
          <configuration>
            <additionalparam>-Xdoclint:none</additionalparam>
          </configuration>
        </plugin>`
then comment this code
``
